### ISSUE TITLE
PCC & IGR calculation error

### ISSUE THREAD

**Issue by mohantyanindita93** [HuangWBill/SVM-LSM-Toolbox#3]
![Screenshot 2024-05-08 105620](https://github.com/HuangWBill/SVM-LSM-Toolbox/assets/169231413/16d1353c-932a-4b6f-acf3-e41bc1c8ff5e)
Sir, I am this error multiple times. Please resolve this issue.

**Comment by HuangWBill** [comment]
Please correctly install the necessary Python libraries according to the "Installation Instructions and Toolbox Introduction" file.
